export class Constants {
    static SUBSCRIPTION_TYPE_SQS = 'SQS';
    static GOLANG_LAMBDA_TYPE = 'GOLANG';
    static TRIGGER_TYPE_KINESIS = 'KINESIS';
    static TRIGGER_TYPE_SQS = 'SQS';
    static TRIGGER_TYPE_CRON = 'CRON';
    static DEQUEUING_TYPE_LAMBDA = 'LAMBDA';
    static DEQUEUING_TYPE_LAMBDA_FIREHOSE = 'LAMBDA_FIREHOSE';
    static REDIS_HOST_ENV_KEY = 'REDIS_HOST';
    static SECRET_ACCESS_ENV_KEY = 'AWS_SECRET_SERVICES_NAME';
    static SQS_DQL_AMPLITUDE_URL_ENV_KEY = 'SQS_AMPLITUDE_DLQ_URL';
    static SQS_DQL_FIREHOSE_URL_ENV_KEY = 'SQS_FIREHOSE_DLQ_URL';
    static SNS_TOPIC_QUEUING_ENV_KEY = 'SNS_QUEUING_SQS_ARN';
    static FIREHOSE_ACCESS_ENV_KEY = 'FIREHOSE_NAME';
    static TRIGGER_TYPE_KINESIS_BATCH_SIZE_DEFAULT = 6 //Value in MBs;
    static TRIGGER_TYPE_KINESIS_BATCH_WINDOWS_DEFAULT = 60 //Value in Seconds;
    static TRIGGER_TYPE_SQS_BATCH_SIZE_DEFAULT = 50 //Value in Seconds;
    static TRIGGER_TYPE_SQS_BATCH_WINDOWS_DEFAULT = 60 //Value in Seconds;
  }